version: '3.8'

services:
  westbudget:
    # Byt ut 'ditt_anvandrnamn' mot ditt Docker Hub-användarnamn
    image: 800121/westbudget:latest
    container_name: westbudget
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Du ville spara bilderna här (på din NAS):
      - /mnt/data/media/apps/trunas-server/WestBudget/uploads:/app/WestBudget/uploads
    environment:
      # Use local postgres database service name 'postgres'
      - DATABASE_URL=postgresql://westbudget:securepassword@postgres:5432/westbudget
      - APPDATA=/app
      - JWT_SECRET_KEY=change_this_to_something_secret_if_you_want
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: westbudget_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: westbudget
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: westbudget
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
